2024-04-03 13:52:40 UTC
Windows-10-10.0.19045
Ren'Py 8.2.0.24012702

Early init took 0.13s
Loading error handling took 0.06s
Loading script took 0.45s
Loading save slot metadata took 0.06s
Loading persistent took 0.00s
<store.MouseDisplayable object at 0x000000000508ab50>
Running init code took 0.10s
Loading analysis data took 0.03s
Analyze and compile ATL took 0.00s
Reloading save slot metadata took 0.04s
Index archives took 0.00s
Backing up script files to 'C:\\Users\\LENOVO\\AppData\\Roaming/RenPy/backups\\KTPVisualNovel':
Dump and make backups took 0.12s
Cleaning cache took 0.00s
Making clean stores took 0.00s
Initial gc took 0.14s
DPI scale factor: 1.000000
nvdrs: Loaded, about to disable thread optimizations.
nvdrs: b"Couldn't load nvlib." (can be ignored)
Creating interface object took 0.01s
Cleaning stores took 0.00s
Init translation took 0.21s
Build styles took 0.07s
Load screen analysis took 0.00s
Analyze screens took 0.13s
Save screen analysis took 0.15s
Prepare screens took 1.62s
Save pyanalysis. took 0.00s
Save bytecode. took 0.10s
Running _start took 0.00s
Interface start took 0.19s

Initializing gl2 renderer:
primary display bounds: (0, 0, 1366, 768)
swap interval: 1 frames
Windowed mode.
Vendor: "b'Intel'"
Renderer: b'Intel(R) HD Graphics 5500'
Version: b'4.4.0 - Build 20.19.15.4642'
Display Info: None
Screen sizes: virtual=(1920, 1080) physical=(1366, 705) drawable=(1366, 705)
Maximum texture size: 4096x4096
Screen sizes: virtual=(1920, 1080) physical=(1366, 705) drawable=(1366, 705)
Maximum texture size: 4096x4096

Full traceback:
  File "game/pia/mainpia.rpy", line 23, in script
    show text "Chapter I\nThe Choosen One" with Pause(1.5)
  File "D:\fanbase_project\KTPVisualNovel\renpy\ast.py", line 1363, in execute
    renpy.exports.with_statement(trans, paired=paired)
  File "D:\fanbase_project\KTPVisualNovel\renpy\exports.py", line 1781, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "D:\fanbase_project\KTPVisualNovel\renpy\display\core.py", line 1548, in do_with
    return self.interact(trans_pause=True,
  File "D:\fanbase_project\KTPVisualNovel\renpy\display\core.py", line 2165, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "D:\fanbase_project\KTPVisualNovel\renpy\display\core.py", line 2814, in interact_core
    self.draw_screen(root_widget, fullscreen_video, (not fullscreen_video) or video_frame_drawn)
  File "D:\fanbase_project\KTPVisualNovel\renpy\display\core.py", line 1352, in draw_screen
    surftree = renpy.display.render.render_screen(
  File "render.pyx", line 486, in renpy.display.render.render_screen
  File "render.pyx", line 260, in renpy.display.render.render
  File "D:\fanbase_project\KTPVisualNovel\renpy\display\layout.py", line 900, in render
    surf = render(child, width, height, cst, cat)
  File "render.pyx", line 170, in renpy.display.render.render
  File "render.pyx", line 260, in renpy.display.render.render
  File "renpy/common/00mousedisplayable.rpy", line 74, in render
    self.cursor = self.cursors[name][0]._duplicate(None)
KeyError: 'pia'

While running game code:
  File "game/pia/mainpia.rpy", line 23, in script
    show text "Chapter I\nThe Choosen One" with Pause(1.5)
  File "renpy/common/00mousedisplayable.rpy", line 74, in render
    self.cursor = self.cursors[name][0]._duplicate(None)
KeyError: 'pia'
While handling exception:
Traceback (most recent call last):
  File "D:\fanbase_project\KTPVisualNovel\renpy\execution.py", line 596, in run
    node.execute()
  File "D:\fanbase_project\KTPVisualNovel\renpy\ast.py", line 1363, in execute
    renpy.exports.with_statement(trans, paired=paired)
  File "D:\fanbase_project\KTPVisualNovel\renpy\exports.py", line 1781, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "D:\fanbase_project\KTPVisualNovel\renpy\display\core.py", line 1548, in do_with
    return self.interact(trans_pause=True,
  File "D:\fanbase_project\KTPVisualNovel\renpy\display\core.py", line 2165, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "D:\fanbase_project\KTPVisualNovel\renpy\display\core.py", line 2814, in interact_core
    self.draw_screen(root_widget, fullscreen_video, (not fullscreen_video) or video_frame_drawn)
  File "D:\fanbase_project\KTPVisualNovel\renpy\display\core.py", line 1352, in draw_screen
    surftree = renpy.display.render.render_screen(
  File "render.pyx", line 486, in renpy.display.render.render_screen
  File "render.pyx", line 260, in renpy.display.render.render
  File "D:\fanbase_project\KTPVisualNovel\renpy\display\layout.py", line 900, in render
    surf = render(child, width, height, cst, cat)
  File "render.pyx", line 170, in renpy.display.render.render
  File "render.pyx", line 260, in renpy.display.render.render
  File "renpy/common/00mousedisplayable.rpy", line 74, in render
    self.cursor = self.cursors[name][0]._duplicate(None)
KeyError: 'pia'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\fanbase_project\KTPVisualNovel\renpy\display\error.py", line 140, in report_exception
    renpy.game.invoke_in_new_context(
  File "D:\fanbase_project\KTPVisualNovel\renpy\game.py", line 293, in invoke_in_new_context
    return callable(*args, **kwargs)
  File "D:\fanbase_project\KTPVisualNovel\renpy\display\error.py", line 48, in call_exception_screen
    return renpy.ui.interact(mouse="screen", type="screen", suppress_overlay=True, suppress_underlay=True)
  File "D:\fanbase_project\KTPVisualNovel\renpy\ui.py", line 301, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "D:\fanbase_project\KTPVisualNovel\renpy\display\core.py", line 2165, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "D:\fanbase_project\KTPVisualNovel\renpy\display\core.py", line 2814, in interact_core
    self.draw_screen(root_widget, fullscreen_video, (not fullscreen_video) or video_frame_drawn)
  File "D:\fanbase_project\KTPVisualNovel\renpy\display\core.py", line 1352, in draw_screen
    surftree = renpy.display.render.render_screen(
  File "render.pyx", line 486, in renpy.display.render.render_screen
  File "render.pyx", line 260, in renpy.display.render.render
  File "D:\fanbase_project\KTPVisualNovel\renpy\display\layout.py", line 900, in render
    surf = render(child, width, height, cst, cat)
  File "render.pyx", line 170, in renpy.display.render.render
  File "render.pyx", line 260, in renpy.display.render.render
  File "renpy/common/00mousedisplayable.rpy", line 83, in render
    _, xo, yo = self.cursors[name]
KeyError: 'pia'

Full traceback:
  File "D:\fanbase_project\KTPVisualNovel\renpy\bootstrap.py", line 359, in bootstrap
    renpy.main.main()
  File "D:\fanbase_project\KTPVisualNovel\renpy\main.py", line 635, in main
    run(restart)
  File "D:\fanbase_project\KTPVisualNovel\renpy\main.py", line 145, in run
    renpy.execution.run_context(True)
  File "D:\fanbase_project\KTPVisualNovel\renpy\execution.py", line 955, in run_context
    context.run()
  File "game/pia/mainpia.rpy", line 23, in script
    show text "Chapter I\nThe Choosen One" with Pause(1.5)
  File "lib/python3.9/future/utils/__init__.py", line 444, in raise_
  File "game/pia/mainpia.rpy", line 23, in script
    show text "Chapter I\nThe Choosen One" with Pause(1.5)
  File "D:\fanbase_project\KTPVisualNovel\renpy\ast.py", line 1363, in execute
    renpy.exports.with_statement(trans, paired=paired)
  File "D:\fanbase_project\KTPVisualNovel\renpy\exports.py", line 1781, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "D:\fanbase_project\KTPVisualNovel\renpy\display\core.py", line 1548, in do_with
    return self.interact(trans_pause=True,
  File "D:\fanbase_project\KTPVisualNovel\renpy\display\core.py", line 2165, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "D:\fanbase_project\KTPVisualNovel\renpy\display\core.py", line 2814, in interact_core
    self.draw_screen(root_widget, fullscreen_video, (not fullscreen_video) or video_frame_drawn)
  File "D:\fanbase_project\KTPVisualNovel\renpy\display\core.py", line 1352, in draw_screen
    surftree = renpy.display.render.render_screen(
  File "render.pyx", line 486, in renpy.display.render.render_screen
  File "render.pyx", line 260, in renpy.display.render.render
  File "D:\fanbase_project\KTPVisualNovel\renpy\display\layout.py", line 900, in render
    surf = render(child, width, height, cst, cat)
  File "render.pyx", line 170, in renpy.display.render.render
  File "render.pyx", line 260, in renpy.display.render.render
  File "renpy/common/00mousedisplayable.rpy", line 74, in render
    self.cursor = self.cursors[name][0]._duplicate(None)
KeyError: 'pia'

While running game code:
  File "game/pia/mainpia.rpy", line 23, in script
    show text "Chapter I\nThe Choosen One" with Pause(1.5)
  File "game/pia/mainpia.rpy", line 23, in script
    show text "Chapter I\nThe Choosen One" with Pause(1.5)
  File "renpy/common/00mousedisplayable.rpy", line 74, in render
    self.cursor = self.cursors[name][0]._duplicate(None)
KeyError: 'pia'
