I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/pia/goodpia.rpy", line 1233, in script
    hide pia with dissovle
  File "game/pia/goodpia.rpy", line 1233, in <module>
    hide pia with dissovle
NameError: name 'dissovle' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/pia/goodpia.rpy", line 1233, in script
    hide pia with dissovle
  File "D:\fanbase_project\KTPVisualNovel\renpy\ast.py", line 1359, in execute
    paired = renpy.python.py_eval(self.paired)
  File "D:\fanbase_project\KTPVisualNovel\renpy\python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "D:\fanbase_project\KTPVisualNovel\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/pia/goodpia.rpy", line 1233, in <module>
    hide pia with dissovle
NameError: name 'dissovle' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.2.0.24012702
WGV:Dreamcatcher 
Fri Jul 26 08:45:43 2024
